### PR TITLE
Made multi-query actually work. :-) Some of that was tricky.

### PR DESCRIPTION
**Pull request by staleyLANL**
Made its error handling consistent with that of other query functions.
Gave it good, informative diagnostics too.
Adjusted operator() function signatures so new overloads all work properly.
Added some helper functions for certain diagnostic printing.
size_t is really std::size_t.
Needed char[N] in one of the traits classes.
Small comments and code tweaks here and there.

### CODE REVIEW

**Comment by staleyLANL** [comment]
Complete, working example:

```
#include "GNDStk.hpp"
using namespace njoy::GNDStk::core;

int main()
{
   tree t("n-094_Pu_239.xml");

   auto info = t(
      // as usual, --s downgrade allow::many to allow::one for query
      reactionSuite,
      PoPs,
      chemicalElements,
      --chemicalElement,
      isotopes,
      --isotope + [](const auto &node){ return node(symbol) == "Pu236"; },
      (
         symbol | // meta
         A |      // meta
         nuclides // child
      )
   );

   assert(std::get<0>(info) == "Pu236");
   assert(std::get<1>(info) == "236");

   // <nuclides> has no metadata
   assert(std::get<2>(info).metadata.size() == 0);

   // <nuclides> has one <nuclide> child
   assert(std::get<2>(info).children.size() == 1);
   assert(std::get<2>(info).children[0]->name == "nuclide");
}
```

**Comment by whaeck** [comment]
@staleyLANL You should make that into a test ;-)

**Comment by whaeck** [comment]
@staleyLANL I tried the multi-query objects with the v1.9 branch, it works as advertised. I did realise that I'll have to test the node references in the case where I have an interface with a node that has children (like axes and constant1d).

**Comment by staleyLANL** [comment]
@whaeck By the way, with the multi-query object being built with bitwise-or rather than comma, you should no longer need the parentheses.

**Review by whaeck — APPROVED** [review]

**Pull request merged**
